### ISSUE TITLE
All Coq Proofs Should End in QED

### ISSUE THREAD

**Issue by brandon-sisler** [brandon-sisler/Intros-Blockly#4]
Currently our generated Coq text only begins proofs with the correct "Proof." statement, but it does not conclude them in the correct manner, that is, with a "Qed."

**Comment by StevenClontz** [comment]
Issues are a good idea. If you get stumped with any of them, assign them to me using the right sidebar.

**Comment by brandon-sisler** [comment]
Aha, an electronic option to move the load to you. I like it, thanks

**Comment by StevenClontz** [comment]
Lol I mean I can say no. But I'm happy to use this opportunity to illustrate some GitHub workflows. (-:
