### ISSUE TITLE
Color Scheme is boring and probably not good for colorblind users.

### ISSUE THREAD

**Issue by brandon-sisler** [brandon-sisler/Intros-Blockly#5]
Looking to learn how saturation and brightness work on block color, and also to make the palette more interesting and variable.

**Comment by StevenClontz** [comment]
Via da5392bfee5d0812b4095749c1a2f0026f36850f ?

A trick: if your commit message says something like "Did a thing. Closes #5" then GitHub knows to mark that issue as closed automatically.
