### ISSUE TITLE
Document how to update live site with new versions

### ISSUE THREAD

**Issue by brandon-sisler** [brandon-sisler/Intros-Blockly#8]
[brandon-sisler.github.io/Intros-Blockly/](https://brandon-sisler.github.io/Intros-Blockly/) does not update with our commits, I suspect, but am not sure how to confirm, that it has something to do with us switching the main branch.

**Comment by StevenClontz** [comment]
It's not a bug, it's a feature! :wink:

But I should document how to update the live site when desired.

**Comment by StevenClontz** [comment]
Oh I did this already but didn't turn your attention (or my own I guess) to it I suppose. https://github.com/brandon-sisler/Intros-Blockly#deploying
