### ISSUE TITLE
Editing Saturation and Value

### ISSUE THREAD

**Issue by brandon-sisler** [brandon-sisler/Intros-Blockly#9]
Blockly's color scheme defaults saturation at 45% and value at 65%, I think both should be 100% by default so we can still use HSV but with a better color palette.

**Comment by StevenClontz** [comment]
Generally I don't trust my artistic taste and defer to default stylings when provided - no problem i fyou want to investigate this yourself though!

**Comment by brandon-sisler** [comment]
I have colors I like now. So problem solved.

**Comment by StevenClontz** [comment]
Again I'm guessing via da5392bfee5d0812b4095749c1a2f0026f36850f (you never know when you want this stuff cross-referenced in your project history) (-:
